### get users
GET http://localhost:8080/api/users
Authorization: Bearer


### get user by token
GET http://localhost:8080/api/user
Authorization: Bearer


### get user by id
GET http://localhost:8080/api/user/0
Authorization: Bearer